CREATE DATABASE IF NOT EXISTS zawody
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE zawody;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE zawodnik (
  id INT AUTO_INCREMENT PRIMARY KEY,
  imie VARCHAR(50) NOT NULL,
  nazwisko VARCHAR(80) NOT NULL
);

CREATE TABLE konkurencja (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nazwa VARCHAR(100) NOT NULL
);

CREATE TABLE wynik (
  id INT AUTO_INCREMENT PRIMARY KEY,
  zawodnik_id INT NOT NULL,
  konkurencja_id INT NOT NULL,
  wartosc DECIMAL(10,2) NOT NULL,
  data_wyniku DATE NOT NULL,
  FOREIGN KEY (zawodnik_id) REFERENCES zawodnik(id) ON DELETE CASCADE,
  FOREIGN KEY (konkurencja_id) REFERENCES konkurencja(id) ON DELETE CASCADE
);
